### ISSUE TITLE
Update to latest cowboy and plug

### ISSUE THREAD

**Issue by hjalet** [christopheradams/plug_rest#6]
Hi is it possible to get `rest_plug` upgraded to latest cowboy and plug? We would like to use the related `phoenix_rest` with latest version 1.4 of Phoenix.
[see related phoenix_rest isssue](https://github.com/christopheradams/phoenix_rest/issues/3)

**Comment by christopheradams** [comment]
PlugRest 0.14.0 drops the Cowboy dependency, and PhoenixRest 0.7.0 should work with both Phoenix 1.3 and 1.4.
